name: wimu
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py
  - audioread=3.0.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - contourpy
  - cycler
  - decorator
  - ffmpeg
  - filelock
  - fonttools
  - freetype
  - gettext
  - gmp
  - gmpy2
  - grpcio
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - lame
  - lazy-loader
  - lazy_loader
  - lcms2
  - lerc
  - libabseil
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libdeflate
  - libexpat
  - libffi
  - libflac
  - libgfortran
  - libiconv
  - liblapack
  - libogg
  - libopus
  - libpng
  - libprotobuf
  - librosa=0.10.2.post1
  - libsndfile
  - libsqlite
  - libtiff
  - libuuid
  - libvorbis
  - libwebp-base
  - libxml2
  - libzlib
  - llvm-openmp
  - llvmlite
  - markdown
  - markupsafe
  - matplotlib-base
  - mpmath
  - msgpack-python
  - munkres
  - ncurses
  - networkx
  - numba
  - numpy
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pandas
  - patsy
  - pillow
  - pip
  - platformdirs
  - pooch
  - protobuf
  - pycparser
  - pydub
  - pyparsing
  - pysocks
  - pysoundfile
  - python=3.10
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytorch
  - pytorch-mutex=1.0
  - pytz
  - pyyaml
  - qhull
  - re2
  - readline
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - setuptools
  - six
  - soxr
  - soxr-python
  - statsmodels
  - sympy
  - tbb
  - tensorboard
  - tensorboard-data-server
  - threadpoolctl
  - tk
  - torchaudio
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - werkzeug
  - wheel
  - xz
  - yaml
  - zipp
  - zlib
  - zstandard
  - zstd